# -*- coding: utf-8 -*-
"""fenced_matrix_alternate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rt2lgZ0P7bcrjKH4cTY7rEQ7RSotUXVW
"""

#take input on your own here
import ast
my_list = ast.literal_eval(input())
m = my_list[0]
n = my_list[1]
#start writing code here
final = [0]*n
final = [list.copy(final) for i in range(m)]
#copy1 = list.copy(final)
for i in range(m):
    for j in range(n):
        if i==0 or j==0 or i==m-1 or j==n-1:
            final[i][j]=1
copy1 = list.copy(final)
for i in copy1:
    print(i)



