# -*- coding: utf-8 -*-
"""fenced_matrix.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Rt2lgZ0P7bcrjKH4cTY7rEQ7RSotUXVW
"""

in_str=input()
in_str=in_str.split(',')
m=int(in_str[0])
n=int(in_str[1])

#make a list with n zeroes
final=[0]*n

#make a matrix of m such lists
final=[list(final) for i in range(m)]
for i in range(m):
    for j in range(n):
        if i==0 or j==0 or i==m-1 or j==n-1:
            final[i][j]=1
            
#print in the fashion as shown in Sample output
for i in final:
    print(i)



